name: Generate Readme
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Read data.json
      id: json
      run: echo "data=$(jq -c . data.json)" >> "$GITHUB_OUTPUT"    
    - name: Generate README.md
      uses: probablykasper/readme-template-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        template: TEMPLATE.md
        output: README.md
        data: ${{ steps.json.outputs.data }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto-update README.md"
          git push
        fi
