name: Custom README Generator

on:
  push:
    paths:
      - 'data.json'
      - 'TEMPLATE.md'
      - 'api/data.json'
      - 'api/TEMPLATE.md'
      - 'ui/data.json'
      - 'ui/TEMPLATE.md'
      - '.github/workflows/generate-Readme.yml'
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Replace Root README
        uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TEMPLATE_FILE: ./TEMPLATE.md
          COMMIT_FILE: ./README.md
          CUSTOM_REPLACER_FILE: ./data.json

      - name: Replace API README
        uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TEMPLATE_FILE: ./api/TEMPLATE.md
          COMMIT_FILE: ./api/README.md
          CUSTOM_REPLACER_FILE: ./api/data.json

      - name: Replace UI README
        uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TEMPLATE_FILE: ./ui/TEMPLATE.md
          COMMIT_FILE: ./ui/README.md
          CUSTOM_REPLACER_FILE: ./ui/data.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md api/README.md ui/README.md
          git commit -m "Update READMEs" || echo "No changes to commit"
          git push