name: Generate Readme

on:
  push:
    paths:
      - 'data.json'
      - 'TEMPLATE.md'
      - '.github/workflows/generate-Readme.yml'
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug file contents
        run: |
         echo "Contents of data.json:"
         cat data.json
         echo "Contents of TEMPLATE.md:"
         cat TEMPLATE.md

      - name: Read data.json into output
        id: json
        run: |
          echo "data=$(jq -c . data.json)" >> "$GITHUB_OUTPUT"

      - name: Generate README.md
        uses: probablykasper/readme-template-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: TEMPLATE.md
          output: README.md
          data: ${{ steps.json.outputs.data }}

      - name: Show generated README.md
        run: cat README.md

      - name: Commit README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add README.md
            git commit -m "Auto-update README.md"
            git push
          fi