name: Custom README Generator

on:
  push:
    paths:
      - 'data.json'
      - 'TEMPLATE.md'
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate README from template
        run: |
          # Read the data.json
          DATA=$(cat data.json)
          # Read the template
          TEMPLATE=$(cat TEMPLATE.md)
          
          # Extract values from JSON and create a README
          README="$TEMPLATE"
          
          # For each key in data.json, replace {{key}} in the template
          for KEY in $(echo "$DATA" | jq -r 'keys[]'); do
            VALUE=$(echo "$DATA" | jq -r --arg k "$KEY" '.[$k]')
            ESCAPED_VALUE=$(printf '%s\n' "$VALUE" | sed 's/[\/&]/\\&/g')
            README=$(echo "$README" | sed "s/{{$KEY}}/$VALUE/g")
          done
          
          # Write the README file
          echo "$README" > README.md
          
          # Show the result
          echo "Generated README.md:"
          cat README.md
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md from template" || echo "No changes to commit"
          git push