name: Generate Readme

on:
  push:
    paths:
      - 'data.json'
      - 'TEMPLATE.md'
      - '.github/workflows/generate-Readme.yml'
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update README.md
        uses: probablykasper/readme-template-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: 'TEMPLATE.md'
          output: 'README.md'
          data: 'data.json'
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push